include: package:lints/recommended.yaml

linter:
  rules:
    - require_trailing_commas  # Requires trailing commas for better darty style
    - public_member_api_docs # All Public API element should be documented
    - always_declare_return_types  # Enforces return types on all functions
    - always_put_control_body_on_new_line  # Ensures control bodies (if, for, etc.) are on a new line
    - annotate_overrides  # Enforces @override annotation on overridden methods
    - avoid_empty_else  # Avoids empty else blocks
    - avoid_annotating_with_dynamic  # Avoids the use of dynamic type annotation
    - avoid_function_literals_in_foreach_calls  # Avoids function literals in forEach calls
    - avoid_types_on_closure_parameters  # Avoids explicit types on closure parameters
    - camel_case_types  # Enforces camel case for type names
    - constant_identifier_names  # Enforces constant identifier names to be uppercase
    - library_prefixes  # Enforces library prefixes
    - non_constant_identifier_names  # Enforces non-constant identifiers to use lowerCamelCase
    - prefer_single_quotes  # Prefers single quotes for strings
    - prefer_final_fields  # Prefers final for fields that are not reassigned
    - prefer_const_constructors  # Prefers const constructors
    - avoid_redundant_argument_values  # Avoids redundant argument values in method calls
    - avoid_unnecessary_containers  # Avoids unnecessary containers in widget trees
    - prefer_is_empty  # Prefers `isEmpty` over `length == 0`
    - prefer_is_not_empty  # Prefers `isNotEmpty` over `length > 0`
