name: shelf_limiter
description: "Rate limiter for package:shelf"
version: 1.0.0
repository: https://github.com/xooniverse/shelf_limiter

environment:
  sdk: ^3.5.2

dependencies:
  shelf: ^1.4.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
